### ISSUE TITLE
Create simple example for webstore

### ISSUE THREAD

**Issue by semanticfire** [rdf-ext-archive/rdf-examples#2]
I'd like to see a browser example both with and without promises how to load a resource from a URL and retrieve all values for a certain triple pattern

e.g.
`http://dbpedia.org/resource/Amsterdam`

and retrieve value of:
`http://dbpedia.org/ontology/abstract`
and
`http://www.w3.org/2000/01/rdf-schema#comment`

**Comment by bergos** [comment]
@semanticfire I think this was at the end solved by using rdf-fetch and/or the rdf-store-sparql, so can we close it?

**Comment by semanticfire** [comment]
exactly
