### ISSUE TITLE
Advanced dereferencing example

### ISSUE THREAD

**Issue by semanticfire** [rdf-ext-archive/rdf-examples#4]
From a browser I would like to use rdf-ext to do a follow your nose type of dereferencing.

e.g. load the dbpedia resource of amsterdam
`http://dbpedia.org/resource/Amsterdam`

and retrieve value of:
`http://dbpedia.org/ontology/part`
and from the resources this points to get
'http://www.w3.org/2000/01/rdf-schema#label
http://dbpedia.org/ontology/populationTotal'

and output a array sorted on population total

( yes I know this can be done with sparql on dbpedia, but thats not the point of this question )

**Comment by bergos** [comment]
Added example, including [HTML version](http://htmlpreview.github.io/?http://raw.githubusercontent.com/rdf-ext/rdf-examples/develop/fetch-dbpedia-2.html).
