### ISSUE TITLE
factory not giving quads back?

### ISSUE THREAD

**Issue by l00mi** [rdf-ext-archive/rdf-examples#5]
The quads are not actually quad instances and thus miss the .toCannonical() function: https://github.com/rdf-ext/rdf-examples/blob/develop/parse-jsonld-to-dataset.js

**Comment by bergos** [comment]
`.toCannonical()` was removed from the RDFJS spec. I added `rdf-ext` as factory to the parser. `rdf-ext` terms and quads have the `.toCannonical()` and `.toString()` methods.
